version: "3.8"
name: ${DATABASE_DOCKER_CONTAINER_NAME}
services:
  postgres:
    image: postgres:15
    container_name: ${DATABASE_DOCKER_CONTAINER_NAME}_database
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  meilisearch:
    container_name: ${DATABASE_DOCKER_CONTAINER_NAME}_meilisearch
    image: getmeili/meilisearch:latest
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    networks:
      - meilisearch
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped

volumes:
  db_data:

networks:
  meilisearch:
    driver: bridge