version: "3.8"
name: ${DATABASE_DOCKER_CONTAINER_NAME}
services:
  postgres:
    image: postgres:15
    container_name: ${DATABASE_DOCKER_CONTAINER_NAME}_database
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: